### ISSUE TITLE
Can't get this to work with Craft 2.5

### ISSUE THREAD

**Issue by zizther** [carlcs/craft-assetmetadata#1]
I am trying to get the length of an MP3 file. I have followed your example, but the template breaks because of this `{% set metadata = craft.assetMetadata.getData(asset) %}`

**Comment by carlcs** [comment]
Sorry, but I have not tested it with Craft 2.5 beta myself. I will look into this issue and will probably have this fixed before the 2.5 release.

**Comment by zizther** [comment]
No worries. It was more of a heads up.
Look forward to the next release

**Comment by carlcs** [comment]
Ok @zizther, I just tested the plugin with Craft 2.5 and wasn't able to reproduce your error. Could you please give a bit more detail on what you mean with "the template breaks", what's the error you're seeing?

**Comment by zizther** [comment]
Thanks for testing this out.
Looking at it further, it maybe something i am doing.
What do I need to pass into the tag.

This is what i currently have:

```
{% for track in tracks %}
    {% set metadata = '' %}

    {% for asset in track.mp3 %}
        {% set metadata = craft.assetMetadata.getData(asset.url) %}
    {% endfor %}

    {{ metadata.playtime_string }}
{% endfor %}
```

**Comment by carlcs** [comment]
Use `getData(asset)` instead of `getData(asset.url)`.
