### ISSUE TITLE
Migration error when attempting to update from Craft 3.7.11 to 3.7.13

### ISSUE THREAD

**Issue by ademers** [carlcs/craft-assetmetadata#11]
### Description

I get the following migration error when attempting to update from from Craft 3.7.11 to 3.7.13. I had no issues updating to previous versions of 3.7 Migration file: https://github.com/carlcs/craft-assetmetadata/blob/v3/src/migrations/m180919_000000_craft3.php

```
Checking for pending migrations ...
Total 1 new Asset Metadata migration to be applied:
    - m180919_000000_craft3

Backing up the database ... done
*** applying m180919_000000_craft3
    > update in {{%fields}} ... done (time: 0.002s)
Exception: Undefined index: defaultValue (/home/vagrant/sites/example/vendor/carlcs/craft-assetmetadata/src/migrations/m180919_000000_craft3.php:39)
#0 /home/vagrant/sites/example/vendor/carlcs/craft-assetmetadata/src/migrations/m180919_000000_craft3.php(39): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/home/vagrant/s...', 39, Array)
#1 /home/vagrant/sites/example/vendor/craftcms/cms/src/db/Migration.php(52): carlcs\assetmetadata\migrations\m180919_000000_craft3->safeUp()
#2 /home/vagrant/sites/example/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#3 /home/vagrant/sites/example/vendor/craftcms/cms/src/console/controllers/MigrateController.php(384): yii\console\controllers\BaseMigrateController->migrateUp('m180919_000000_...')
#4 [internal function]: craft\console\controllers\MigrateController->actionAll()
#5 /home/vagrant/sites/example/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /home/vagrant/sites/example/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#7 /home/vagrant/sites/example/vendor/yiisoft/yii2/console/Controller.php(184): yii\base\Controller->runAction('all', Array)
#8 /home/vagrant/sites/example/vendor/yiisoft/yii2/base/Module.php(534): yii\console\Controller->runAction('all', Array)
#9 /home/vagrant/sites/example/vendor/yiisoft/yii2/console/Application.php(181): yii\base\Module->runAction('migrate/all', Array)
#10 /home/vagrant/sites/example/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#11 /home/vagrant/sites/example/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('migrate/all', Array)
#12 /home/vagrant/sites/example/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#13 /home/vagrant/sites/example/craft(22): yii\base\Application->run()
#14 {main}
*** failed to apply m180919_000000_craft3 (time: 0.033s)


0 from 1 migrations were applied.

Migration failed. The rest of the migrations are canceled.
```

### Steps to reproduce

1. Attempt to update from Craft 3.7.11 to 3.7.13
2. Run `./craft migrate/all --interactive=0`
3. See migration error above.

### Additional info

- Craft version: 3.7.11/3.7.13
- PHP version: 7.2.34
- Database driver & version: MySQL 5.5.5
- Plugins & versions: https://cln.sh/XqY7ObS7m5RoXQA8EGo1

Apparently, changing:

``` php
$newSubfields[$key] = [
    'name' => $subfield['name'],
    'handle' => $subfield['handle'],
    'template' => $subfield['defaultValue'],
];
```
to 
```php
$newSubfields[$key] = [
    'name' => $subfield['name'],
    'handle' => $subfield['handle'],
    'template' => $subfield['defaultValue'] ?? null,
];
 ``` 
 may fix it.

**Comment by carlcs** [comment]
Hi Andrea, got to admit it’s been a while since I’ve last been in touch with this plugin. So I have it running in 3.7, but somehow new assets don’t have much useful data in the metadata variable. Might be an issue with Craft removing EXIF data on upload now.

Now to your migration issue, did you have the plugin uninstalled or disabled for a while? I don’t understand why Craft tries to suddenly run the migration.

**Comment by ademers** [comment]
Hi Christian, Thanks for the quick response! I did not uninstall the plugin and don't remember disabling it, at least not in Production. I also thought it was odd that the migration error only appeared when going from 3.7.11 to 3.7.13 instead of in initial upgrade from 3.6.x to 3.7. This is why I initially posted this issue in Craft repo at https://github.com/craftcms/cms/issues/9890

**Comment by carlcs** [comment]
It is a Craft 2 to 3 migration and should have run either a) when you upgraded to Craft 3 or b) when you installed the plugin in Craft 3. So basically the first time Craft 3 found the migration.

My guess is this migration did indeed run back then, but for some reason you’ve now got no row with a name “m180919_000000_craft3” in your migrations table. Could this be the case?

If it’s indeed missing you could add it manually with this SQL query.

```sql
INSERT INTO `migrations` (`track`, `name`, `applyTime`, `dateCreated`, `dateUpdated`, `uid`)
VALUES
	('plugin:asset-metadata', 'm180919_000000_craft3', '2021-10-20 13:32:42', '2021-10-20 13:32:42', '2021-10-20 13:32:42', 'b1d8dfc5-77c4-4eb8-898c-b03c2b9091be');

```

**Comment by ademers** [comment]
@carlcs I don't see that row, so I'll give your suggestion a try and let you know how it goes.

**Comment by ademers** [comment]
@carlcs Added row in local dev DB and updated to Craft 3.7.18.2 without any migration issues. Will add row to production DB before pushing changes. Thanks!
