### ISSUE TITLE
Help with install

### ISSUE THREAD

**Issue by terraindesign** [carlcs/craft-assetmetadata#12]
Probably user error, but having problems installing this. After successful running `composer require carlcs/craft-assetmetadata`, running `php craft plugin/install asset-metadata` fails with the following error. Running craft 4.3.1

```
❯ php craft plugin/install asset-metadata
*** installing asset-metadata
*** failed to install asset-metadata: No plugin exists with the handle "asset-metadata".
```

I have confirmed that the files are in the vendor directory. Not sure what I'm doing wrong. Any ideas? Thanks.

**Comment by carlcs** [comment]
I have just tested installing it on a brand new 4.3.1 install and it worked for me without issues. Can you please send me your composer.json and composer.lock files?

**Comment by terraindesign** [comment]
Thanks Carlcs! You are definitely going above any beyond. Much appreciated.

It’s the strangest thing. Like I said, it might very well be user error. This is a new install of craft 4 with lot’s of changes that I’m still trying to wrap my head around —but haven't encountered this issue with composer / craft install before. It’s definitely in composer.json, composer.lock, and vendor folder. And I successfully installed a couple other plugins from command line to make sure it wasn’t a system issue. So weird.

Thanks again.
Douglas

**Comment by carlcs** [comment]
Hey Douglas, this is a weird issue indeed. I am thinking it might have to do with the other plugins you have installed. I’d like to reproduce this error but I‘d need your composer files for that. Cheers, Christian
