### ISSUE TITLE
Craft 4 support?

### ISSUE THREAD

**Issue by taya13** [carlcs/craft-assetmetadata#13]
When/if this will have craft4 support?

**Comment by carlcs** [comment]
Hey, you running into problems installing?

**Comment by taya13** [comment]
I have not tried yet, I assumed it was not possible, as craft writes "UNKNOWN" in "craft 4 upgrade" info page.
![image](https://user-images.githubusercontent.com/43302003/222857147-f9b52ad5-824c-48ec-8da5-37ba9f1425a5.png)
So it should have no problems with craft4?

By the way, its missing logo and documentation link goes to wrong plugin:
https://github.com/carlcs/craft-deleteentryversions
![image](https://user-images.githubusercontent.com/43302003/222857071-97f13c15-981d-42db-ae09-c61ec313aaff.png)

**Comment by carlcs** [comment]
Yes, it works with Craft 4. I assume it says unknown in the update guide because Craft gets the info from the plugin store, and I never got around to write docs and get it listed there.

**Comment by carlcs** [comment]
@taya13 here’s a tip how you can check compatibility, see this line in "requirements" in composer.json
https://github.com/carlcs/craft-assetmetadata/blob/43a06d92d5653c25fa93357c6e5615966bda342e/composer.json#L27

I’ll need to fix the link to the repo, thanks! But the logo is actually meant to look like this, a file with i for info in it. 🤷‍♂️
