### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by owldesign** [carlcs/craft-assetmetadata#2]
I can't seem to get it to work. I have followed the instructions but when clicking refresh nothing happens.

Here are my steps:
1. Created asset source that uploads files to S3 bucket
2. Created assetmetadata field and added it to the asset source field layout
3. Created Photo Upload filed and added it to Entries fields layout (asset field handle is `photo`)
4. After making new Entry and uploading Photo, I double click the photo thumbnail and click `Refresh` button to get my ISO field populated.

At this point the spinner spins and nothing happens.
Here are some screenshots. 
Can you take a look and see what I'm doing wrong? Thanks!

I even tried replacing `jpg` with my asset field handle `photo` but still nothing.
![screen shot 2016-03-08 at 11 27 56 pm](https://cloud.githubusercontent.com/assets/438764/13628305/004d28dc-e586-11e5-8c91-a2b128787575.png)

![photoexif](https://cloud.githubusercontent.com/assets/438764/13628336/482f1a8e-e586-11e5-88a2-ba514bca14dd.gif)

**Comment by carlcs** [comment]
Hmm.. it doesn't look like you did something that is obviously wrong. What's really irritating to me is that you can't even store a manually typed in value to the field. I don't know how to help without further info, could you contact me on Craft Slack?

**Comment by carlcs** [comment]
A good first step debugging this would be to replace the

``` Twig
{{ metadata.jpg.exif.EXIF.ISOSpeedRatings is defined ? 'ISO ' ~ metadata.jpg.exif.EXIF.ISOSpeedRatings }}
```

with some hardcoded value

``` Twig
{{ 400 }}
```

**Comment by owldesign** [comment]
It started working again. Also I missed the part there I need to install Numbers plugin and after that it worked like a charm. Thanks for the plugin!
